import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createSemanticTest, serializeSemanticTestYaml } from '@verity/semantic-model';
import type { Framework } from '@verity/core';

export interface ScaffoldOptions {
  readonly projectName: string;
  readonly appDescription?: string;
  readonly baseUrl?: string;
}

export interface ScaffoldResult {
  readonly filesCreated: number;
  readonly framework: Framework;
}

const PLAYWRIGHT_VERSION = '1.49.0';

function pomXml(projectName: string): string {
  const artifact = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>${artifact}</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <name>${projectName}</name>
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <playwright.version>${PLAYWRIGHT_VERSION}</playwright.version>
    <junit.version>5.11.3</junit.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>\${playwright.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>\${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.2</version>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.5.0</version>
      </plugin>
    </plugins>
  </build>
</project>
`;
}

function loginPageJava(baseUrl: string): string {
  return `package com.example.pages;

import com.microsoft.playwright.Page;

/** Login page object — scaffolded by Verity (${baseUrl}). */
public class LoginPage {
  private final Page page;
  private final String baseUrl;

  public LoginPage(Page page, String baseUrl) {
    this.page = page;
    this.baseUrl = baseUrl;
  }

  public void open() {
    page.navigate(baseUrl + "/login");
  }

  public void login(String email, String password) {
    page.getByLabel("Email").fill(email);
    page.getByLabel("Password").fill(password);
    page.getByRole(com.microsoft.playwright.options.AriaRole.BUTTON,
        new Page.GetByRoleOptions().setName("Sign in")).click();
  }
}
`;
}

function smokeTestJava(): string {
  return `package com.example.tests;

import com.example.pages.LoginPage;
import com.microsoft.playwright.*;
import org.junit.jupiter.api.*;

/** Smoke test placeholder — generated by Verity scaffold. */
public class SmokeTest {
  static Playwright playwright;
  static Browser browser;
  static BrowserContext context;
  static Page page;

  @BeforeAll
  static void launch() {
    playwright = Playwright.create();
    browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));
  }

  @AfterAll
  static void close() {
    if (browser != null) browser.close();
    if (playwright != null) playwright.close();
  }

  @BeforeEach
  void createContext() {
    context = browser.newContext();
    page = context.newPage();
  }

  @AfterEach
  void closeContext() {
    context.close();
  }

  @Test
  void loginPageLoads() {
    LoginPage login = new LoginPage(page, System.getProperty("baseUrl", "https://example.com"));
    login.open();
  }
}
`;
}

function gitignore(): string {
  return `target/
.idea/
*.iml
.classpath
.project
.settings/
.playwright/
`;
}

function readme(projectName: string, description: string): string {
  return `# ${projectName}

${description}

Scaffolded by [Verity](https://github.com) — AI-Native Test Engineering Workspace.

## Run tests

\`\`\`bash
mvn test
\`\`\`

Semantic tests live in \`.verity/tests/\`. Framework code is generated from those definitions.
`;
}

function starterSemanticTest(baseUrl: string) {
  return createSemanticTest({
    id: 'smoke-login',
    name: 'Smoke — login page loads',
    adapter: 'playwright-java',
    promptVersion: 'scaffold-v1',
    steps: [
      {
        id: 1,
        intent: 'Open the login page',
        action: 'navigate',
        context: `Application base URL ${baseUrl}`,
        expected: 'Login form is visible',
        confidence: 0.92,
        locators: [
          { ref: 'LoginPage.open', strategy: 'role', value: 'Sign in', invented: false },
        ],
      },
      {
        id: 2,
        intent: 'Verify login form renders',
        action: 'assert',
        context: 'Email and password fields present',
        expected: 'User can start authentication flow',
        confidence: 0.9,
        locators: [
          { ref: 'LoginPage.email', strategy: 'label', value: 'Email', invented: false },
        ],
      },
    ],
  });
}

/**
 * Scaffolds a Playwright Java Maven project with page objects and a starter semantic test (M1.5).
 */
export function scaffoldPlaywrightJava(repoRoot: string, options: ScaffoldOptions): ScaffoldResult {
  const baseUrl = options.baseUrl ?? 'https://example.com';
  const description =
    options.appDescription?.trim() ||
    'Playwright Java end-to-end test project scaffolded by Verity.';

  const dirs = [
    join(repoRoot, 'src', 'test', 'java', 'com', 'example', 'tests'),
    join(repoRoot, 'src', 'test', 'java', 'com', 'example', 'pages'),
    join(repoRoot, '.verity', 'tests'),
  ];
  for (const dir of dirs) {
    mkdirSync(dir, { recursive: true });
  }

  const files: Array<[string, string]> = [
    [join(repoRoot, 'pom.xml'), pomXml(options.projectName)],
    [join(repoRoot, 'README.md'), readme(options.projectName, description)],
    [join(repoRoot, '.gitignore'), gitignore()],
    [join(repoRoot, 'src', 'test', 'java', 'com', 'example', 'pages', 'LoginPage.java'), loginPageJava(baseUrl)],
    [join(repoRoot, 'src', 'test', 'java', 'com', 'example', 'tests', 'SmokeTest.java'), smokeTestJava()],
    [
      join(repoRoot, '.verity', 'tests', 'smoke-login.yaml'),
      serializeSemanticTestYaml(starterSemanticTest(baseUrl)),
    ],
  ];

  for (const [filePath, content] of files) {
    writeFileSync(filePath, content, 'utf8');
  }

  const framework: Framework = {
    adapterId: 'playwright-java',
    version: PLAYWRIGHT_VERSION,
    buildTool: 'maven',
    testFramework: 'JUnit 5',
    pattern: 'page-object-model',
  };

  return { filesCreated: files.length, framework };
}
