import type { RepositoryIndexSnapshot } from '@verity/adapter-contract';
import { transpileResult, type TranspileResult } from '@verity/adapter-contract';
import type { SemanticTest } from '@verity/semantic-model';
import { transpileStep } from './transpile-step.js';

/**
 * Transpile a semantic test to Playwright TypeScript spec file (M1.7).
 */
export function transpileSemanticTest(
  test: SemanticTest,
  _index: RepositoryIndexSnapshot,
): TranspileResult {
  const className = toFileBase(test.id);
  const relPath = `tests/${className}.spec.ts`;
  const stepLines = test.steps.flatMap((step) => transpileStep(step, '    '));

  const content = `import { test, expect } from '@playwright/test';

/** Generated by Verity adapter-playwright-typescript from ${test.id}.yaml */
test('${escapeQuote(test.name)}', async ({ page }) => {
${stepLines.join('\n')}
});
`;

  return transpileResult([{ path: relPath, content, type: 'create' }], []);
}

function toFileBase(slug: string): string {
  return slug.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
}

function escapeQuote(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
