import type { RepositoryIndexSnapshot } from '@verity/adapter-contract';
import { transpileResult, type TranspileResult } from '@verity/adapter-contract';
import type { SemanticTest } from '@verity/semantic-model';
import { patchPageObjects } from './page-object-patcher.js';
import { transpileStep } from './transpile-step.js';

const DEFAULT_PACKAGE = 'com.verity.generated';
const DEFAULT_TEST_ROOT = 'src/test/java';

/**
 * Transpile a semantic test to Playwright Java source files (M3 E3-S2 T2–T4).
 */
export function transpileSemanticTest(
  test: SemanticTest,
  index: RepositoryIndexSnapshot,
  repoRoot: string,
): TranspileResult {
  const warnings: string[] = [];
  const packageName = packageFromConventions(index);
  const className = toClassName(test.id);
  const methodName = toMethodName(test.id);
  const relPath = `${testSourceRoot(index)}/${packageName.replace(/\./g, '/')}/${className}.java`;

  const stepLines = test.steps.flatMap((step) => transpileStep(step, '      '));

  const content = `package ${packageName};

import com.microsoft.playwright.*;
import com.microsoft.playwright.options.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** Generated by Verity adapter-playwright-java from ${test.id}.yaml */
public class ${className} {

  @Test
  void ${methodName}() {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));
      BrowserContext context = browser.newContext();
      Page page = context.newPage();

${stepLines.join('\n')}

      browser.close();
    }
  }
}
`;

  const files = [{ path: relPath, content, type: 'create' as const }];
  const pagePatches = patchPageObjects(repoRoot, test.steps, index);
  if (pagePatches.length > 0) {
    warnings.push(`Patched ${pagePatches.length} page object file(s) with invented locators.`);
  }

  return transpileResult([...files, ...pagePatches], warnings);
}

function packageFromConventions(index: RepositoryIndexSnapshot): string {
  const root = index.conventions.packageRoot;
  if (root?.includes('java/')) {
    const segment = root.split('java/')[1]?.replace(/\//g, '.');
    if (segment) return `${segment}.generated`;
  }
  return DEFAULT_PACKAGE;
}

function testSourceRoot(index: RepositoryIndexSnapshot): string {
  return index.conventions.testSourceRoot ?? DEFAULT_TEST_ROOT;
}

function toClassName(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toMethodName(slug: string): string {
  const className = toClassName(slug);
  return className.charAt(0).toLowerCase() + className.slice(1);
}
